CREATE OR REPLACE PACKAGE PKG_KAFKA
AS

vURL_PROD varchar2(100) :='';
vURL_TEST varchar2(100) :='';

-- Отправка сообщений в KAFKA PROD
FUNCTION SEND_MESSAGE(vTOPIC 	IN VARCHAR, 
					cVALUE 		IN CLOB, 
					vKEY 		IN VARCHAR2 DEFAULT NULL) RETURN NUMBER;
				
-- Отправка сообщений в KAFKA TEST
FUNCTION SEND_MESSAGE_TEST(vTOPIC 	IN VARCHAR, 
						cVALUE 		IN CLOB, 
						vKEY 		IN VARCHAR2 DEFAULT NULL) RETURN NUMBER;
					
-- Отправка сообщений в KAFKA PROD
PROCEDURE SEND_MESSAGE(vTOPIC 	IN VARCHAR, 
					cVALUE 		IN CLOB, 
					vKEY 		IN VARCHAR2 DEFAULT NULL);
				
-- Отправка сообщений в KAFKA TEST
PROCEDURE SEND_MESSAGE_TEST(vTOPIC 	IN VARCHAR, 
						cVALUE 		IN CLOB, 
						vKEY 		IN VARCHAR2 DEFAULT NULL);
				
END PKG_KAFKA;