CREATE OR REPLACE PACKAGE BODY PKG_KAFKA
AS

FUNCTION SEND_MESSAGE(vTOPIC 	IN VARCHAR, 
					cVALUE 		IN CLOB, 
					vKEY 		IN VARCHAR2,
					vURL		IN VARCHAR2) RETURN NUMBER
AS
	req 			UTL_HTTP.REQ;
	resp 			UTL_HTTP.RESP;
	vBODY			CLOB;
	nBODY_LENGTH	NUMBER;
	nAMOUNT			NUMBER := 25000;
	nOFFSET 		NUMBER := 1;
	vBUFFER			VARCHAR2 (32767);
	vLINE 			VARCHAR2 (4000);
	vTEXT 			VARCHAR2 (4000);
	nSTATUS_CODE	NUMBER := -1;
BEGIN
	req := UTL_HTTP.BEGIN_REQUEST(url => vURL, METHOD => 'POST' );
	UTL_HTTP.SET_BODY_CHARSET('UTF-8');

	vBODY := '{"topic": '||vTOPIC||', "value":'||cVALUE||', "key":'||vKEY||'}';

	nBODY_LENGTH := DBMS_LOB.GETLENGTH(vBODY);
	
	IF nBODY_LENGTH > 32768 THEN
		WHILE (nOFFSET < nBODY_LENGTH) LOOP
			BEGIN
				DBMS_LOB.READ (vBODY,
								nAMOUNT,
                        		nOFFSET,
                        		vBUFFER);

			EXCEPTION WHEN OTHERS THEN
				NULL;
			END; 

			BEGIN              
				UTL_HTTP.WRITE_TEXT (req, vBUFFER);
			EXCEPTION WHEN OTHERS THEN 
				NULL;
			END;
				nOFFSET := nOFFSET + nAMOUNT;
            END LOOP;
		ELSE
			UTL_HTTP.WRITE_TEXT(req, vBODY); 
	END IF;

	resp := UTL_HTTP.GET_RESPONSE(req);

	nSTATUS_CODE := resp.status_code;

 	LOOP
		UTL_HTTP.READ_LINE(resp, vLINE, TRUE );
		vTEXT := vTEXT || vLINE;
	END LOOP;

	UTL_HTTP.END_RESPONSE(resp);	
	UTL_HTTP.END_REQUEST(req);

	RETURN nSTATUS_CODE;
EXCEPTION WHEN UTL_HTTP.END_OF_BODY THEN
	UTL_HTTP.END_RESPONSE (resp);
	RETURN nSTATUS_CODE;
WHEN OTHERS THEN
	UTL_HTTP.END_RESPONSE(resp);
	UTL_HTTP.END_REQUEST(req);
	RETURN nSTATUS_CODE;
END SEND_MESSAGE;

FUNCTION SEND_MESSAGE(vTOPIC 	IN VARCHAR, 
					cVALUE 		IN CLOB, 
					vKEY 		IN VARCHAR2) RETURN NUMBER
AS
	nSTATUS_CODE	NUMBER := -1;
BEGIN
	nSTATUS_CODE := SEND_MESSAGE(vTOPIC 	=> vTOPIC, 
							cVALUE 		=> cVALUE, 
							vKEY 		=> vKEY,
							vURL 		=> vURL_PROD);
	RETURN nSTATUS_CODE;
END SEND_MESSAGE;

FUNCTION SEND_MESSAGE_TEST(vTOPIC 	IN VARCHAR, 
						cVALUE 		IN CLOB, 
						vKEY 		IN VARCHAR2) RETURN NUMBER
AS
	nSTATUS_CODE	NUMBER := -1;
BEGIN
	nSTATUS_CODE := SEND_MESSAGE(vTOPIC 	=> vTOPIC, 
								cVALUE 		=> cVALUE, 
								vKEY 		=> vKEY,
								vURL 		=> vURL_TEST);
	RETURN nSTATUS_CODE;
END SEND_MESSAGE_TEST;


END PKG_KAFKA;